source "http://rubygems.org"
gem "daemons"
gem "oauth"
gem "twitter"
gem "sinatra"
gem "thin"
gem "moji"
gem "em-http-request"
gem "em-websocket"
gem "async_sinatra"
gem "json" if RUBY_VERSION < "1.9.0"
