source "http://rubygems.org"
gem "daemons"
gem "oauth"
gem "twitter"
gem "sinatra"
gem "sinatra-reloader"
gem "thin"
gem "moji"
gem "em-http-request"
gem "em-websocket"
gem "async_sinatra"
gem "http_accept_language"
gem "erubis"
gem "activesupport"  # Implicit dependency of http_accept_language
gem "json" if RUBY_VERSION < "1.9.0"
